# Generated by Django 3.1.3 on 2020-11-05 16:38

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('id', models.UUIDField(default=uuid.UUID('3f2b051c-8d3f-4cba-a01f-b2664869f651'), editable=False, primary_key=True, serialize=False)),
            ],
            options={
                'default_related_name': 'account',
            },
        ),
        migrations.CreateModel(
            name='Wallet',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('id', models.UUIDField(default=uuid.UUID('693e60e3-f753-4f2a-b58e-a3274a1dfe8f'), editable=False, primary_key=True, serialize=False)),
                ('wallet_balance', models.FloatField(default=0)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='wallet', to='wallet.account')),
            ],
            options={
                'default_related_name': 'wallet',
            },
        ),
        migrations.CreateModel(
            name='WalletTransx',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('id', models.UUIDField(default=uuid.UUID('ff920c48-c123-46a5-9f57-8c81ae1f7f53'), editable=False, primary_key=True, serialize=False)),
                ('reference_id', models.UUIDField(default=uuid.UUID('1d62af81-0fe4-4e65-9e5e-34ba797791bb'))),
                ('amount', models.FloatField(default=0)),
                ('transx_type', models.BooleanField(default=0)),
                ('status', models.BooleanField(default=1)),
                ('wallet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='wallet_transaction', to='wallet.wallet')),
            ],
            options={
                'default_related_name': 'wallet_transaction',
            },
        ),
    ]
