# Generated by Django 3.1.3 on 2020-11-05 17:07

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('wallet', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='id',
            field=models.UUIDField(default=uuid.UUID('76d7ff77-6272-4411-a2d3-0fbc32db868b'), editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='wallet',
            name='id',
            field=models.UUIDField(default=uuid.UUID('db903e07-d73d-4533-9c0f-ce998ec16404'), editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='wallettransx',
            name='id',
            field=models.UUIDField(default=uuid.UUID('121baae6-1445-4686-8add-25ceca3730e1'), editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='wallettransx',
            name='reference_id',
            field=models.UUIDField(default=uuid.UUID('38e2020d-ee55-43f5-bb42-a36a726263bc')),
        ),
    ]
